language: python
sudo: false

python: 
  - 2.7
  - 3.5
  - 3.6

env:
- PANDAS_VERSION=0.18.1
- PANDAS_VERSION=0.19.2
- PANDAS_VERSION=0.20.3

matrix:
  exclude:
  - python: 3.6
    env: PANDAS_VERSION=0.18.1

before_install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  # required for using mkl-service
  - export MKL_THREADING_LAYER=GNU
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n testenv --yes python=$TRAVIS_PYTHON_VERSION numpy pandas=$PANDAS_VERSION flake8
  - pip install nose_parameterized

before_script:
  - "flake8 opat"

script:
  - nosetests $TESTCMD

notifications:
  email: false

branches:
  only:
    - master